### ISSUE TITLE
INTEL folder not found and C compiler cannot create executables

### ISSUE THREAD

**Issue by shipanhua** [mstsuite/MuST#16]
I cannot find *INTEL* folder in the source code of *FFTW* & *LIBXC* & *P3DFFT*. How to compile the *INTEL* folder?

thx

**Comment by shipanhua** [comment]
https://github.com/mstsuite/MuST/blob/76ad2901eef160b05628e2abef583f47b39353b4/architecture/ubuntu-gnu-mpich#L7-L13

**Comment by wangy2014** [comment]
The path shown in the architecture file, ubuntu-gnu-mpich, is just an example. You need to set the path based on your system environment. Let me use FFTW as an example here:
If your system has FFTW installed, for example, under /usr/local/FFTW/fftw-3.3.8, then you should set "FFTW_PATH =  /usr/local/FFTW/fftw-3.3.8". 
If your system has multiple versions of FFTW installation, and the one built with intel compiler is installed under /usr/local/FFTW/fftw-3.3.8/INTEL. you will need to set "FFTW_PATH =  /usr/local/FFTW/fftw-3.3.8/INTEL", if you want to use intel compiler to build MuST . 
If you don't have FFTW installed on your system, you may just set "FFTW_PATH =". In this case, MuST will install FFTW for you under MuST/external/. 
I hope this helps.

**Comment by shipanhua** [comment]
``` log
[root@node131 MuST-master]# make ubuntu-gnu-mpich 
.
make[1]: Entering directory `/opt/MuST-master/external'
if [ ! -d libxc/LibXC ]; then \
DIR_NAME="libxc-5.0.0" && cd libxc && rm -f LibXC && tar xfz libxc.tar.gz && \
ln -fs $DIR_NAME LibXC; fi
if [ ! -e libxc/LibXC/./lib/libxc.a ]; then \
cd libxc/LibXC && echo $PWD && ./configure --prefix=$PWD/. CC=mpicc.mpich CFLAGS="-O3" FC=mpif90.mpich FFLAGS="-O3" && make clean && make && make install; fi
/opt/MuST-master/external/libxc/LibXC
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a sed that does not truncate output... /bin/sed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... mpicc.mpich
checking whether the C compiler works... no
configure: error: in `/opt/MuST-master/external/libxc/LibXC':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[1]: *** [libxc] Error 77
make[1]: Leaving directory `/opt/MuST-master/external'
make: *** [ubuntu-gnu-mpich] Error 2

```

**Comment by wangy2014** [comment]
The architecture usually needs to be modified, since each system has different software environment. For example, the MPI wrapper for C may be called mpicc on your systems, while in ubuntu-gnu-mpich it assumes that the wrapper is called mpicc.mpich (to distinguish from other MPI wrapper, e.g. openmpi, for C). If your system has mpich installed, and the wrapper is called mpicc, you will need to modify this architecture file by setting "CC=mpicc". The same rule applies to CXX, F77, FC, MPICC as well.

**Comment by shipanhua** [comment]
Thanks for your help on compiling! Additionally, I've learnt the Tutorial file and could u please guide me for more information in the Ouput file, such as force and distance between any two atoms?
