### ISSUE TITLE
Setting lattice type, documentation of settings?

### ISSUE THREAD

**Issue by fospald** [mstsuite/MuST#19]
Hi, I can't find any information on how to set the lattice type for an KKR CPA calculation.
In general is there any documentation for the input_files, except for the tutorial?

**Comment by wangy2014** [comment]
As you may have already known, there is a CuZn example under MuST/Tutorial/CuZn/BCC that shows how to set up a KKR-CPA calculation. Unfortunately, at this point, we don't have a documentation to give further instructions for running KKR-CPA calculations. It is on our to-do list.
