### ISSUE TITLE
How to generate new potential

### ISSUE THREAD

**Issue by hitliaomq** [mstsuite/MuST#29]
Dear developer,

I want to do some calculations which containing Sn, and I found there is no Sn potential in the potentials folder. How to generate the potential for Sn.

I know the *newa* and *newss* are used to produce the potential, but I'm not quite clear with some settings in the input file.
1. How to set the mixing parameter?
2. If the structure is not bcc and not fcc, how to set the crystal type?

Thank you very much.

**Comment by meisenbach** [comment]
The potentials in mstsuite/lsms/Potentials have the same format as MuST starting potentials. It might be able to use those. A Sn potential is available there.

**Comment by hitliaomq** [comment]
@meisenbach Thank you very much. I will download those potentials.
