### ISSUE TITLE
Can MuST handle structures more than cubic

### ISSUE THREAD

**Issue by hitliaomq** [mstsuite/MuST#30]
Dear developer,

I'm trying to use MuST to calculate the elastic constants, which requires the energy or stress of deformed structures (not cubic). 

All the samples and tutorials included in the package are cubic, even for Mg, Hf and Ti, whose stable structures are HCP.

Though the position.dat can handle any structure, I noticed that all the start potentials are FCC or BCC (1 for fcc and 2 for bcc in the input file of newss). If newss can generate potentials more than cubic, what the number is for other structure, e.g. bct.

Thank you very much.

**Comment by wangy2014** [comment]
Hi,
The MuST code can be applied to other structures than the cubic ones. The potential generated by newss only serves as a starting potential and is expected to change as the SCF iteration goes. It does not matter which structure (FCC or BCC) you use to generate the starting potential. Of course, a better starting potential will allow for faster or more stable convergence. In this regard, what is more important is the lattice constant you use to generate the potential. The general rule is: You want to use a lattice constant that corresponds to an atomic volume which is very close to the atomic volume of the atom in your targeted system.
Best!

**Comment by hitliaomq** [comment]
@wangy2014 Dear Prof.Wang,
Thank you very much for your kind reply.
